services:
  traefik:
    image: "traefik:v2.6"
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - letsencrypt:/letsencrypt
    command:
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.email=a.khssnv@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
  
  superstring:
    build: .
    container_name: supersting
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.supersting.loadbalancer.server.port=4000"
      - "traefik.http.routers.supersting.entrypoints=websecure"
      - "traefik.http.routers.supersting.rule=Host(`superstring.g.khassanov.xyz`)"
      - "traefik.http.routers.supersting.tls=true"
      - "traefik.http.routers.supersting.tls.certresolver=letsencrypt"

volumes:
  letsencrypt: {}
